name: Pruebas Biblioteca - CI

# Ejecutar workflow en pushes y pull requests hacia main
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    # Máquina virtual Ubuntu
    runs-on: ubuntu-latest

    # Servicios necesarios
    services:
      mysql:
        image: mysql:8.0

        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: biblioteca

        ports:
          - 3306:3306

        # Health check para asegurar que MySQL esté disponible
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        command: --default-authentication-plugin=mysql_native_password

    steps:
      # Descargar repositorio
      - name: Checkout del código
        uses: actions/checkout@v4

      # Instalar cliente MySQL
      - name: Instalar cliente MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      # Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v4

        with:
          python-version: "3.11"

      # Esperar conexión MySQL y cargar BD
      - name: Preparar Base de Datos
        run: |
          echo "Esperando a MySQL..."

          until mysqladmin ping -h 127.0.0.1 -u root -proot --silent; do
            sleep 2
          done

          echo "MySQL iniciado correctamente"

          # Crear base de datos si no existe
          mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE IF NOT EXISTS biblioteca;"

          # Importar archivo SQL
          mysql -h 127.0.0.1 -u root -proot biblioteca < biblioteca.sql

      # Instalar dependencias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest requests

      # Ejecutar pruebas de microservicios
      - name: Ejecutar pruebas
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: root
          DB_NAME: biblioteca

        run: |
        
          python services/paises/app.py &
          sleep 5
          pytest services/paises/test_paises.py

          python services/usuarios/app.py &
          sleep 5
          pytest services/usuarios/test_usuarios.py

          python services/autores/app.py &
          sleep 5
          pytest services/autores/test_autores.py

          python services/editoriales/app.py &
          sleep 5
          pytest services/editoriales/test_editoriales.py